name: signature
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  dartx: ^0.7.1
  flutter:
    sdk: flutter
  flutter_svg: ^0.22.0
  get: 4.3.6
  google_fonts: ^2.1.0
  velocity_x: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # assets:
  #   - lib/app/assets/icons/
